export const BASE_URL = 'http://185.116.194.159:34345/';
// export const BASE_URL = 'https://geoback.medsystem.online/';

export const filterKeys = [
  { case: 'Аллерго код', color: '#710bff', id: 'alergoCod', maxPage: 9 },
  { case: 'Инсульт', color: '#2f5597', id: 'stroke', maxPage: 6 },
  { case: 'Поли травма', color: '#ffda07', id: 'polyOfTrauma', maxPage: 4 },
  { case: 'Ожоги', color: '#ff7a00', id: 'burns', maxPage: 4 },
  { case: 'Беременность', color: '#0fb13c', id: 'pregnancy', maxPage: 6 },
  { case: 'Ножевые ранения', color: '#896008', id: 'knifeWounds', maxPage: 4 },
  { case: 'Код Кардио', color: '#f15a5a', id: 'codeCardio', maxPage: 6 },
  {
    case: 'Желудочно-кишечные кровотечения',
    color: '#0b8dff',
    id: 'gastrointestinalBleeding',
    maxPage: 4,
  },
];

export const LABEL_OF_CASES = {
  stroke: [
    'Данные по пациенту',
    'Начато лечение',
    'Физиологические показатели',
    'Сбор анамнеза 1/2',
    'Сбор анамнеза 2/2',
  ],
  alergoCod: [
    'Данные по пациенту',
    'Информация о вызове',
    'Сбор информации 1/2',
    'Сбор информации 2/2',
    'Витальные показатели',
    'Предполагаемый аллерген',
    'Проведённая терапия',
    'Дополнительно',
    'Оценка после терапии',
  ],
  polyOfTrauma: [
    'Данные по пациенту',
    'Сбор информации 1/2',
    'Сбор информации 2/2',
    'Проведённая терапия',
  ],
  burns: [
    'Данные по пациенту',
    'Витальные показатели',
    'Сбор информации',
    'Проведённая терапия',
  ],
  pregnancy: [
    'Данные по пациенту',
    'Паритет',
    'Действия медицинского персонала',
    'Профилактика судорог',
    'Гипотензивное лечение',
    'Оценка состояния плода',
  ],
  knifeWounds: [
    'Данные по пациенту',
    'Сбор информации 1/2',
    'Сбор информации 2/2',
    'Проведённая терапия',
  ],
  codeCardio: [
    'Данные по пациенту',
    'Клиническая картина',
    'Первый медицинский контакт',
    'ЭКГ (до 10 минут от контакта!)',
    'Догоспитальное лечение',
    'Передача пациента',
  ],
};

// POINT_OF_CASES - указать все кейсы

export const POINT_OF_CASES = {
  stroke: {
    level1: [
      'birthdayDate',
      'comments',
      'homeAddress',
      'patientFullName',
      'patientINN',
      'sex',
      'userLocation',
    ],
    level2: [
      'firstSymptomsTimeHh',
      'firstSymptomsTimeMm',
      'firstSymptomsDate',
      'handDisplacement',
      'saggingFace',
      'speechDisorders',
      'lossOfBalance',
      'visionProblems',
      'firstSymptomsTime_unknown',
      'firstSymptomsDate_unknown',
    ],
    level3: [
      'beginStrokeTreatment',
      'intravenousAccess',
      'patientTakingAnticoagulants',
      'takeECG',
      'deliveryTimeHh',
      'deliveryTimeMm',
    ],
    level4: [
      'bloodSugarLevel',
      'bodyTemperature',
      'arterialPressureS',
      'arterialPressureD',
      'patientBodyWeight',
      'patientAge',
    ],
    level5: [
      'intracranialHemorrhages',
      'majorSurgeriesOrSevereInjuries',
      'surgicalInterventions',
      'myocardialInfarction',
      'stroke',
      'arterialPuncture',
    ],
    level6: [
      'smallOperations',
      'cardiovascularDiseases',
      'acuteInfectiousDisease',
      'hemorrhages',
      'onmk',
      'convulsions',
      'hemorrhagicStroke',
      'SACStroke',
      'ischemicStroke',
      'transient_cerebrovascular_accident',
      'unknown_accident',
      'noteChecklistSMP',
    ],
  },
  alergoCod: {
    level1: [
      'birthdayDate',
      'comments',
      'homeAddress',
      'patientFullName',
      'patientINN',
      'sex',
      'userLocation',
    ],
    level2: [
      'startTimeOfSimptomsHh',
      'startTimeOfSimptomsMm',
      'timeOfCallingHh',
      'timeOfCallingMm',
      'timeOfArrivingHh',
      'timeOfArrivingMm',
      'dateOfReview',
      'timeOfReviewHh',
      'timeOfReviewMm',
      'nameOfParamedic',
      'numberOfBrigade',
    ],
    level3: ['sign', 'rash', 'swelling', 'shortnessOfBreath', 'tachypnea'],
    level4: [
      'painInTheStomach',
      'pressureReduction',
      'passOff',
      'convulsions',
      'cyanosis',
    ],
    level5: [
      'ad',
      'pulse',
      'breathingRate',
      'saturation',
      'temperature',
      'glucoseLevel',
    ],
    level6: [
      'isMedicin',
      'isFoodProduct',
      'isStingInsect',
      'isAllergen',
      'isNotEstablished',
      'medicin',
      'foodProduct',
      'stingInsect',
      'allergen',
      'notEstablished',
    ],
    level7: [
      'isAdrenaline',
      'isDexamethasone',
      'isSuprastin',
      'isSolutions',
      'isInhalation',
      'isOtherapy',
      'adrenaline',
      'dexamethasone',
      'suprastin',
      'solutions',
      'inhalation',
      'otherapy',
    ],
    level8: [
      'isCatheter',
      'isEkg',
      'isTrachealIntubation',
      'isCardiopulmonaryResuscitation',
    ],
    level9: [
      'adBefore',
      'adAfter',
      'pulseBefore',
      'pulseAfter',
      'saturationBefore',
      'saturationAfter',
      'compliencesBefore',
      'compliencesAfter',
      'consciousnessBefore',
      'consciousnessAfter',
    ],
  },
  polyOfTrauma: {
    level1: [
      'birthdayDate',
      'comments',
      'homeAddress',
      'patientFullName',
      'patientINN',
      'sex',
      'userLocation',
    ],
    level2: [
      'clearConsciousness',
      'coma',
      'stupor',
      'sopor',
      'ad',
      'pulse',
      'saturation',
    ],
    level3: [
      'localizationOfWound',
      'bloodLoss',
      'symptomOfPaleSpot',
      'wound',
      'bloodLossCheck',
    ],
    level4: [
      'anesthesia',
      'instalOfPeripheralCatheter',
      'infusion',
      'timeOfAppOfTourniquetPolyHh',
      'timeOfAppOfTourniquetPolyMm',
      'pressureBandage',
    ],
  },
  burns: {
    level1: [
      'birthdayDate',
      'comments',
      'homeAddress',
      'patientFullName',
      'patientINN',
      'sex',
      'userLocation',
    ],
    level2: [
      'isThermalBurn',
      'isChemicalBurn',
      'isInhalationBurn',
      'isElectricBurn',
      'ad',
      'pulse',
      'saturation',
      'isClearConsciousness',
      'isStunning',
      'isSopor',
      'isComa',
    ],
    level3: ['symptomPaleSpots', 'localizationOfPlaces', 'selectedZones'],
    level4: [
      'analgesia',
      'pressureBandage',
      'tourniquetHh',
      'tourniquetMm',
      'catheter',
      'infusion',
    ],
  },
  pregnancy: {
    level1: [
      'birthdayDate',
      'comments',
      'homeAddress',
      'patientFullName',
      'patientINN',
      'sex',
      'userLocation',
    ],
    level2: ['paritet', 'application'],
    level3: [
      'ad',
      'headPain',
      'breakVision',
      'painEpigastricRegion',
      'vomiting',
      'tremor',
      'oliguria',
      'catheterizationOfVein',
      'bladderCatheterization',
      'noteToOther',
      'amnioticFluid',
      'blood',
      'other',
    ],
    level4: ['startingDose', 'maintenanceDose'],
    level5: ['firstNifedipineInjection', 'secondNifedipineInjection'],
    level6: ['movementFetus'],
  },
  knifeWounds: {
    level1: [
      'birthdayDate',
      'comments',
      'homeAddress',
      'patientFullName',
      'patientINN',
      'sex',
      'userLocation',
    ],
    level2: [
      'clearConsciousness',
      'coma',
      'stupor',
      'sopor',
      'ad',
      'pulse',
      'saturation',
    ],
    level3: ['symptomOfPaleSpot', 'localizationOfWound', 'bloodLoss'],
    level4: [
      'anesthesia',
      'instalOfPeripheralCatheter',
      'infusion',
      'timeOfAppOfTourniquetKnifeHh',
      'timeOfAppOfTourniquetKnifeMm',
      'pressureBandage',
    ],
  },
  codeCardio: {
    level1: [
      'birthdayDate',
      'comments',
      'homeAddress',
      'patientFullName',
      'patientINN',
      'sex',
      'userLocation',
    ],
    level2: [
      'isChestPain',
      'natureChestPain',
      'localizationChestPain',
      'irradiationChestPain',
      'durationChestPain',
      'isShortnessBreath',
      'isWeakness',
      'isNausea',
      'isLossOfConsciousness',
      'clinicalPictureOther',
    ],
    level3: [
      'firstMedicalContactHh',
      'firstMedicalContactMm',
      'adLeftHand',
      'adRightHand',
      'pulse',
      'pubreathingRatese',
      'rhythm',
      'deficit',
      'chdd',
      'satO',
      'isSignsOfHF_edema',
      'isSignsOfHF_wheezing',
      'physicalExaminationOther',
    ],
    level4: [
      'isECCarriedOut',
      'isElevation',
      'isDepression',
      'isFibrillation',
      'isBlockade',
      'ecgOther',
    ],
    level5: [
      'isASK',
      'isClopidogrel',
      'isHeparin',
      'isNitroglycerin',
      'isMorphine',
      'isTLT',
      'startTLTDate',
      'finishTLTDate',
      'prehospitalTreatmentOther',
    ],
    level6: [
      'timeOfBuginOfSymptomsHh',
      'timeOfBuginOfSymptomsMm',
      'timeOfHospitaTransferlHh',
      'timeOfHospitaTransferlMm',
      'isVenousAccess',
      'adLeftHandOfHospitaTransfer',
      'adRightHandOfHospitaTransfer',
      'pulseOfHospitaTransfer',
      'breathingRateOfHospitaTransfer',
      'rhythmOfHospitaTransfer',
      'deficitOfHospitaTransfer',
      'chddOfHospitaTransfer',
      'satOOfHospitaTransfer',
      'isSignsOfHF_edemaOfHospitaTransfer',
      'isSignsOfHF_wheezingOfHospitaTransfer',
      'physicalExaminationOtherOfHospitaTransfer',
    ],
  },
  gastrointestinalBleeding: {
    level1: [
      'birthdayDate',
      'comments',
      'homeAddress',
      'patientFullName',
      'patientINN',
      'sex',
      'userLocation',
    ],
    level2: [
      'clearConsciousness',
      'coma',
      'stupor',
      'sopor',
      'ad',
      'pulse',
      'saturation',
    ],
    level3: [
      'symptomOfPaleSpot',
      'localizationOfGastroIntestinalBleeding',
      'vomitingBlood',
      'stoolWithBlood',
      'colorOfBlood',
      'bloodLoss',
    ],
    level4: [
      'anesthesia',
      'instalOfPeripheralCatheter',
      'infusion',
      'timeOfAppOfTourniquetGastroHh',
      'timeOfAppOfTourniquetGastroMm',
      'pressureBandage',
    ],
  },
};
